### ISSUE TITLE
galoy client not returning errors

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/stablesats-rs#115]
When gql returns an error its not being passed back to the caller.

**Comment by enigbe** [comment]
The current state of error handling by the `galoy_client` checks for the base `errors` (see JSON below), returning that if found, and returns a custom error for nested `errors`, like the one in `data.user_login.errors`. The custom error does not appear to capture the actual content of the nested error returned, therefore what the caller receives is an error that's not as descriptive as it should be. I have started working on a fix that'll address this.

```
[
    {
        "data": {
            "user_login": {
                "auth_token": null,
                "errors": [
                    {
                        "message": "Nested error message",
                        "path": null
                    }
                ]
            }
        },
        "errors": null
    }
]
```
