### ISSUE TITLE
Make reds subscription more resilient

### ISSUE THREAD

**Issue by bodymindarts** [GaloyMoney/stablesats-rs#119]
Any time we are subscribing to redis messages - we need an outer loop that reconnects the subscriber if something fails.
Ideally handled in our `Subscriber` client and not in calling code.
-> implies returning an mpsc or something like that.

First investgate expected behaviour of client library.

**Comment by bodymindarts** [comment]
> First investgate expected behaviour of client library.

after looking closer it should already be re-connecting. Perhaps the `custom-recconect-errors` feature is missing - but not sure what is going on.

**Comment by enigbe** [comment]
The client library reconnects fine. I tried to recreate an environment similar to the one we have in staging locally. It is not quite exact but enough to test how the library behaves when there is a network partition. The challenge here may be linked to the sentinel going down during the upgrade.

**Comment by bodymindarts** [comment]
Upstream already has tickets for exactly this issue with fixes in flight:
- https://github.com/aembke/fred.rs/issues/62
- https://github.com/aembke/fred.rs/issues/56
- https://github.com/aembke/fred.rs/issues/59
