### ISSUE TITLE
Auto withdrawal will never get triggered as long as a position is open

### ISSUE THREAD

**Issue by zoop-btc** [GaloyMoney/stablesats-rs#341]
Hi,
I've been trying to figure out when stablesats auto-withdraws and looking at the code this path is never taken as long as a position is open.
The `abs_exposure_in_btc` is calculated from `Decimal::from(signed_exposure_in_cents).abs() / btc_price_in_cents;` and `signed_exposure_in_cents` is `current_position_in_cents.usd_cents.into()` coming from the conditionally_spawn_adjust_funding [in the engine](https://github.com/GaloyMoney/stablesats-rs/blob/afe2c4e7c88799b59cb980a3af36ecfc0fe2037b/hedging/src/okex/engine.rs#L147-L160).

https://github.com/GaloyMoney/stablesats-rs/blob/afe2c4e7c88799b59cb980a3af36ecfc0fe2037b/hedging/src/okex/funding_adjustment.rs#L142-L154

`abs_exposure_in_btc.is_zero() ` can never be true as long as a position is open.

So my question is: Is this a bug or have I not understood the code? How can I trigger a withdrawal from okex to galoy otherwise?

Thank you and all the best,
Zoop

**Comment by sebastienverreault** [comment]
Hey Zoop,
The section you are looking at is the terminal condition when your position is closed but you still have funds on the exchange, so it initiates the last withdraw.

The [condition](https://github.com/GaloyMoney/stablesats-rs/blob/afe2c4e7c88799b59cb980a3af36ecfc0fe2037b/hedging/src/okex/funding_adjustment.rs#L168-L179) you are looking for is
when your ratio of exposure to collateral is below the low_bound_ratio_leverage level which by default is 2.0.
So if you use the default leverage bounds, you should have an hysteresis that goes from 2.0 to 4.0, 4 being your your set exchange leverage and anything between being acceptable.

At ~4.0 you have 25% of your exposure in collateral, and might be about to get a margin call / get liquidated.
At 2.0 you have 50%, so a lot of funds in excess of what's required and the idea is to withdraw to a 3.0 level.

Defaults are these:

2.0 as low_bound_ratio_leverage
3.0 as low_safebound_ratio_leverage
3.0 as high_safebound_ratio_leverage
4.0 as high_bound_ratio_leverage

Defined here:

[Hysteresis config](https://github.com/GaloyMoney/stablesats-rs/blob/cac2c2c6c64591be2d8d8eb327245098fd46c9ba/stablesats.yml#L75-L79)
[Hysteresis defaults](https://github.com/GaloyMoney/stablesats-rs/blob/ffe9aa676f9f9e478b17c036f924e86c9938fed7/hedging/src/app/config.rs#L159-L173)

**Comment by zoop-btc** [comment]
@sebastienverreault thank you so much, I had overseen that function! I have a follow up question though. Inside calculate_transfer_out_withdraw it will only withdraw from the exchange if amount_in_btc is zero, otherwise it transfers from trading to funding.

https://github.com/GaloyMoney/stablesats-rs/blob/afe2c4e7c88799b59cb980a3af36ecfc0fe2037b/hedging/src/okex/funding_adjustment.rs#L234

Given that the value is calculated by `trading_available_balance.total_amt_in_btc - ( abs_exposure_in_btc / low_safebound_ratio_leverage )` I just don't see how it can reach zero... and go to the next clause which I want to trigger.

Hopefully it's another dumb mistake on my part.

**Comment by zoop-btc** [comment]
any news on this @sebastienverreault ? We're stuck currently....

**Comment by sebastienverreault** [comment]
This issue has been resolved in #373
