### ISSUE TITLE
Verify that we use the correct bid/ask as per the original implementation

### ISSUE THREAD

**Issue by sebastienverreault** [GaloyMoney/stablesats-rs#64]
Seems like the bid & ask have been switched in at least one occurrence.
https://github.com/GaloyMoney/stablesats-rs/blob/d532597885a176fa47572455c62558345ffab832/price-server/src/app/mod.rs#L67

The reason we want this right is because we need to cross the spread on the order so we want to account for it in the quote to avoid potentially paying the spread each time.

**Comment by bodymindarts** [comment]
Please identify which value in the test is wrong and correct that first.

**Comment by bodymindarts** [comment]
I think we've got this covered now
